export default {
  // 基础变量
  'mui-global-bg': '#f3f6f8',
  'mui-global-bg-normal': '#ffffff',
  'mui-base-bg': '#ffffff',
  'mui-base-bg-dark': '#333854',
  'mui-brand': '#5e7ce0',
  'mui-brand-foil': '#859bff',
  'mui-brand-hover': '#7693f5',
  'mui-brand-active': '#526ecc',
  'mui-brand-active-focus': '#344899',
  'mui-contrast': '#c7000b',
  'mui-text': '#252b3a',
  'mui-text-weak': '#575d6c',
  'mui-aide-text': '#8a8e99',
  'mui-aide-text-stress': '#575d6c',
  'mui-placeholder': '#8a8e99',
  'mui-light-text': '#ffffff',
  'mui-dark-text': '#252b3a',
  'mui-link': '#526ecc',
  'mui-link-active': '#526ecc',
  'mui-link-light': '#96adfa',
  'mui-link-light-active': '#beccfa',
  'mui-line': '#adb0b8',
  'mui-dividing-line': '#dfe1e6',
  'mui-block': '#ffffff',
  'mui-area': '#f8f8f8',
  'mui-danger': '#f66f6a',
  'mui-warning': '#fac20a',
  'mui-waiting': '#9faad7',
  'mui-success': '#50d4ab',
  'mui-info': '#5e7ce0',
  'mui-initial': '#e9edfa',
  'mui-unavailable': '#f5f5f6',
  'mui-shadow': 'rgba(0, 0, 0, 0.2)',
  'mui-light-shadow': 'rgba(0, 0, 0, 0.1)',
  // 图标
  'mui-icon-text': '#252b3a',
  'mui-icon-bg': '#ffffff',
  'mui-icon-fill': '#d3d5d9',
  'mui-icon-fill-hover': '#adb5ce',
  'mui-icon-fill-active': '#5e7ce0',
  'mui-icon-fill-active-hover': '#526ecc',
  // 表单
  'mui-form-control-line': '#adb0b8',
  'mui-form-control-line-hover': '#575d6c',
  'mui-form-control-line-active': '#5e7ce0',
  'mui-form-control-line-active-hover': '#344899',
  'mui-list-item-active-bg': '#5e7ce0',
  'mui-list-item-active-text': '#ffffff',
  'mui-list-item-active-hover-bg': '#526ecc',
  'mui-list-item-hover-bg': '#f2f5fc',
  'mui-list-item-hover-text': '#526ecc',
  'mui-list-item-selected-bg': '#e9edfa',
  'mui-list-item-strip-bg': '#f2f5fc',
  // 禁用
  'mui-disabled-bg': '#f5f5f6',
  'mui-disabled-line': '#dfe1e6',
  'mui-disabled-text': '#adb0b8',
  'mui-primary-disabled': '#beccfa',
  'mui-icon-fill-active-disabled': '#beccfa',
  // 特殊背景色
  'mui-label-bg': '#eef0f5',
  'mui-connected-overlay-bg': '#ffffff',
  'mui-connected-overlay-line': '#526ecc',
  'mui-fullscreen-overlay-bg': '#ffffff',
  'mui-feedback-overlay-bg': '#464d6e',
  'mui-feedback-overlay-text': '#dfe1e6',
  'mui-embed-search-bg': '#f2f5fc',
  'mui-embed-search-bg-hover': '#eef0f5',
  'mui-float-block-shadow': 'rgba(94, 124, 224, 0.3)',
  'mui-highlight-overlay': 'rgba(255, 255, 255, 0.8)',
  'mui-range-item-hover-bg': '#e9edfa',
  // 按钮
  'mui-primary': '#5e7ce0',
  'mui-primary-hover': '#7693f5',
  'mui-primary-active': '#344899',
  'mui-contrast-hover': '#d64a52',
  'mui-contrast-active': '#b12220',
  // 状态
  'mui-danger-line': '#f66f6a',
  'mui-danger-bg': '#ffeeed',
  'mui-warning-line': '#fa9841',
  'mui-warning-bg': '#fff3e8',
  'mui-info-line': '#5e7ce0',
  'mui-info-bg': '#f2f5fc',
  'mui-success-line': '#50d4ab',
  'mui-success-bg': '#edfff9',
  'mui-primary-line': '#5e7ce0',
  'mui-primary-bg': '#f2f5fc',
  'mui-default-line': '#5e7ce0',
  'mui-default-bg': '#f3f6f8',
  // 字体设置相关
  'mui-font-size': '12px',
  'mui-font-size-card-title': '14px',
  'mui-font-size-page-title': '16px',
  'mui-font-size-modal-title': '18px',
  'mui-font-size-price': '20px',
  'mui-font-size-data-overview': '24px',
  'mui-font-size-icon': '16px',
  'mui-font-size-sm': '12px',
  'mui-font-size-md': '12px',
  'mui-font-size-lg': '14px',
  'mui-font-title-weight': 'bold',
  'mui-font-content-weight': 'normal',
  'mui-line-height-base': '1.5',
  // 圆角
  'mui-border-radius': '2px',
  'mui-border-radius-feedback': '4px',
  'mui-border-radius-card': '6px',
  // 阴影
  'mui-shadow-length-base': '0 1px 4px 0',
  'mui-shadow-length-slide-left': '-2px 0 8px 0',
  'mui-shadow-length-slide-right': '2px 0 8px 0',
  'mui-shadow-length-connected-overlay': '0 2px 8px 0',
  'mui-shadow-length-hover': '0 4px 16px 0',
  'mui-shadow-length-feedback-overlay': '0 4px 16px 0',
  'mui-shadow-fullscreen-overlay': '0 8px 40px 0',
  // 动效
  'mui-animation-duration-slow': '300ms',
  'mui-animation-duration-base': '200ms',
  'mui-animation-duration-fast': '100ms',
  'mui-animation-ease-in': 'cubic-bezier(0.5, 0, 0.84, 0.25)',
  'mui-animation-ease-out': 'cubic-bezier(0.16, 0.75, 0.5, 1)',
  'mui-animation-ease-in-out': 'cubic-bezier(0.5, 0.05, 0.5, 0.95)',
  'mui-animation-ease-in-smooth': 'cubic-bezier(0.645, 0.045, 0.355, 1)',
  'mui-animation-linear': 'cubic-bezier(0, 0, 1, 1)',
  // zIndex
  'mui-z-index-full-page-overlay': '1080',
  'mui-z-index-pop-up': '1060',
  'mui-z-index-dropdown': '1052',
  'mui-z-index-modal': '1050',
  'mui-z-index-drawer': '1040',
  'mui-z-index-framework': '1000'
};
